add thetaSketch aggregator
grafadruid/go-druid pull request #41
Opened 2021-04-01 18:30 UTC by chromevoid

2021-04-01 18:33 UTC, vigith commented
please add testing

2021-04-01 20:49 UTC, vigith approved these changes
LGTM

2021-04-02 14:12 UTC, jbguerraz requested changes

2021-04-02 14:12 UTC, jbguerraz commented on builder/aggregation/thetasketch_test.go
> +	// "omitempty" will ignore boolen=false
typo, boolen => boolean

2021-04-02 16:39 UTC, jbguerraz approved these changes
Thank you @chromevoid :+1:

2021-04-02 16:39 UTC, merged