Double sketches
grafadruid/go-druid pull request #60
Opened 2021-12-22 22:17 UTC by cosmic-chichu

2021-12-22 22:24 UTC, vigith requested changes

2021-12-22 22:24 UTC, vigith commented on builder/postaggregation/post_aggregator.go
> +	case "quantilesDoublesSketchToQuantile":
TDigest uses `from` v/s DoublesSketch is using `To`? can we use the same naming convention?

2021-12-22 22:27 UTC, vigith commented on builder/postaggregation/post_aggregator.go
> +	case "quantilesDoublesSketchToQuantile":
it is based on the type specified here: https://druid.apache.org/docs/latest/development/extensions-core/datasketches-quantiles.html#quantile

2021-12-22 22:30 UTC, vigith submitted a review, later dismissed

2021-12-23 20:21 UTC, jbguerraz requested changes
Nice work @cosmic-chichu  :) thank you!

2021-12-23 20:21 UTC, jbguerraz commented on builder/postaggregation/quantiles_doubles_sketch_to_quantile.go
> +	return qf
maybe `return &QuantilesDoublesSketchToQuantileField{}` to save one useless assignation

2021-12-23 20:21 UTC, jbguerraz commented on examples/doubkesSketchExample.go
> +	d, err := druid.NewClient("https://getafix-qal.odldruid-ppd.a.intuit.com")
probably better to replace it with `http://localhost:8888`

2021-12-23 20:21 UTC, jbguerraz commented on examples/doubkesSketchExample.go
> +	table := datasource.NewTable().SetName("o11y-gsapi-apigw")
maybe change the table name for something more generic ? like `double-sketch` or so ?

2021-12-23 20:21 UTC, jbguerraz commented on builder/aggregation/quantiles_doubles_sketch.go
> +	t := &QuantilesDoublesSketch{}
why `t` ? why not `q` instead ?

2021-12-24 00:45 UTC, jbguerraz requested changes
small nitpick

2021-12-24 00:45 UTC, jbguerraz commented on examples/doublesSketchExample.go
> +    		}],
nitpick but wrong indent

2021-12-24 09:19 UTC, jbguerraz approved these changes
LGTM! Thank you again :)

2021-12-24 09:19 UTC, merged